# This is the minimal config file for an NNI experiment.
# Use "nnictl create --config config.yml" to launch this experiment.
# Afterwards, you can check "config_detailed.yml" for more explanation.

searchSpaceFile: search_space.json

trialCommand: python3 main.py
trialCodeDirectory: .

trialGpuNumber: 1
trialConcurrency: 2

#maxExperimentDuration: 24h
#maxTrialNumber: 100

tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize

trainingService:
  platform: local
  useActiveGpu: True

assessor:
  #choice: Medianstop, Curvefitting
  Name: Curvefitting
  classArgs:
    epoch_num: 200
    threshold: 0.80
    start_step: 10
    gap: 1